Sets&Maps
JohnnyShi/USACO pull request #13
Opened 2023-11-07 09:47 UTC by Reditiny

2023-11-08 11:48 UTC, JohnnyShi requested changes

2023-11-08 11:48 UTC, JohnnyShi commented on Bronze/2017/January/01_dont_be_last/DontBeLast.java
> +        positionMap.put("Henrietta", 6);
默认应该都是0

2023-11-08 11:48 UTC, JohnnyShi commented on Bronze/2021/February/01_year_of_the_cow/YearOfTheCow.java
> +    static {
这里使用静态代码块的意义是？感觉对我们的场景意义不大，反而要费时间解释

2023-11-08 11:48 UTC, JohnnyShi commented on Bronze/2021/February/01_year_of_the_cow/YearOfTheCow.java
> +                diff = zodiacMap.get(oldCowZodiac) - zodiacMap.get(newCowZodiac);
比如：Mildred born in previous Dragon year from Bessie
Bessie是1，则Mildred = 4，diff = -3， diff += 12 后为9，那ageMap + diff不就变成 0 + 9 = 9了？55行应该是减吧？这个能过测试用例？

2023-11-08 11:48 UTC, JohnnyShi commented on Silver/2016/December/02_cities_and_states/CitiesAndStates.java
> +            String code = st.nextToken();
命名为cityCode和stateCode

2023-11-08 11:48 UTC, JohnnyShi commented on Silver/2016/December/02_cities_and_states/CitiesAndStates.java
> +    static Map<String, Integer> codeAndStateToCount = new HashMap<>();
这个命名的意思是？

2023-11-08 11:48 UTC, JohnnyShi commented on Silver/2016/December/02_cities_and_states/CitiesAndStates.java
> +            codeAndStateToCount.put(stateAndCity, codeAndStateToCount.get(stateAndCity) + 1);
HashMap有getOrDefault函数

2023-11-08 14:34 UTC, Reditiny commented on Bronze/2021/February/01_year_of_the_cow/YearOfTheCow.java
> +                diff = zodiacMap.get(oldCowZodiac) - zodiacMap.get(newCowZodiac);
可以全过，上一个龙年相差就是9年

2023-11-08 14:35 UTC, Reditiny commented on Bronze/2021/February/01_year_of_the_cow/YearOfTheCow.java
> +    static {
改到 mian 函数里了，放外面只是不想让main函数太臃肿

2023-11-08 14:38 UTC, Reditiny commented on Bronze/2017/January/01_dont_be_last/DontBeLast.java
> +        positionMap.put("Henrietta", 6);
这个map是为了在输入时不用switch，和默认应该没什么关系

2023-11-09 03:00 UTC, Reditiny commented on Bronze/2017/January/01_dont_be_last/DontBeLast.java
> +        positionMap.put("Henrietta", 6);
map是用作数组索引映射，不是牛奶量，最终牛奶量是存在数组里，因为数组方便遍历，map的遍历是无序的

2023-11-09 03:01 UTC, Reditiny commented on Bronze/2021/February/01_year_of_the_cow/YearOfTheCow.java
> +                diff = zodiacMap.get(oldCowZodiac) - zodiacMap.get(newCowZodiac);
嗯，if else 里的逻辑反了，因为Bessie为age 0最后又取了绝对值，所以最终答案是对的

2023-11-09 03:59 UTC, JohnnyShi requested changes

2023-11-09 03:59 UTC, JohnnyShi commented on Bronze/2017/January/01_dont_be_last/DontBeLast.java
> +        // 而 map 的遍历是无序的
那一开始也都是并列奶量为0，都改成0吧

2023-11-09 04:21 UTC, Reditiny commented on Bronze/2017/January/01_dont_be_last/DontBeLast.java
> +        // 而 map 的遍历是无序的
数组默认值是零，这个map存的是索引

2023-11-09 05:25 UTC, JohnnyShi commented on Bronze/2017/January/01_dont_be_last/DontBeLast.java
> +        // 而 map 的遍历是无序的
我感觉用了索引反而复杂了，只用一个hashmap，存名字和产量的映射，然后用hashmap的entryset遍历，找到第一和第二小的值，最后再遍历一遍找到第二小的名字

2023-11-09 05:26 UTC, JohnnyShi requested changes
DontBeLast

2023-11-09 06:56 UTC, JohnnyShi requested changes

2023-11-09 06:56 UTC, JohnnyShi commented on Bronze/2017/January/01_dont_be_last/DontBeLast.java
> +        });
一次遍历可以找到min和secondMin

2023-11-09 07:52 UTC, JohnnyShi approved these changes

2023-11-09 07:52 UTC, merged