Additional
JohnnyShi/USACO pull request #14
Opened 2023-11-07 09:52 UTC by Reditiny

2023-11-08 13:46 UTC, JohnnyShi requested changes

2023-11-08 13:46 UTC, JohnnyShi commented on Bronze/2015/January/03_its_all_about_the_base/ItsAllAboutTheBase.java
> +public class ItsAllAboutTheBase {
最坏情况下是n^2 复杂度，可以另外实现一个nlogn的吗？

2023-11-08 13:46 UTC, JohnnyShi commented on Bronze/2016/US Open/03_field_reduction/FieldReduction.java
> +public class FieldReduction {
保留这种解法；现在的复杂度是对16种组合遍历N，可参考python代码，实现不用遍历全部N的方法

2023-11-08 14:46 UTC, Reditiny commented on Bronze/2015/January/03_its_all_about_the_base/ItsAllAboutTheBase.java
> +public class ItsAllAboutTheBase {
这是O(n)的算法，外面的for是输入有多个case，内层while两个遍历都是单调增加，复杂度O(m+n)。如果二分的话是固定一个二分另一个，复杂度nlogn

2023-11-08 14:59 UTC, Reditiny commented on Bronze/2016/US Open/03_field_reduction/FieldReduction.java
> +public class FieldReduction {
python的三个代码似乎没有一个能过的

2023-11-08 16:33 UTC, JohnnyShi commented on Bronze/2016/US Open/03_field_reduction/FieldReduction.java
> +public class FieldReduction {
v6是验证过都可以过的

2023-11-09 03:21 UTC, JohnnyShi requested changes

2023-11-09 03:21 UTC, JohnnyShi commented on Bronze/2016/US Open/03_field_reduction/FieldReduction2.java
> +                        }
y不会再改变了，这里不需要

2023-11-09 03:29 UTC, Reditiny commented on Bronze/2016/US Open/03_field_reduction/FieldReduction2.java
> +                        }
y为什么不会再改变了，前面删除x的时候可能删到y排序下的第二第三个，这时候如果删了y排序下的第一个，那么第二个第三个是需要跳过的。

2023-11-09 04:04 UTC, JohnnyShi requested changes

2023-11-09 04:04 UTC, JohnnyShi commented on Bronze/2016/US Open/03_field_reduction/FieldReduction2.java
> +                        }
首先先按照x的收尾添加x方向要被移除的点；再按照y的收尾添加y方向要被移除的点；
在这之后调整一次x，是因为y在移除的时候可能移除掉了x的点，这里调整x并没有删除新点，只是找到x的边界值。
因为调整x没有删除新点，所以y不用调整

2023-11-09 04:27 UTC, Reditiny commented on Bronze/2016/US Open/03_field_reduction/FieldReduction2.java
> +                        }
“首先先按照x的收尾添加x方向要被移除的点”，假设这里删除了两个点，分别是按y排序下的第二个和第三个点。“再按照y的收尾添加y方向要被移除的点” 如果这里删除了按y排序下的第一个点，那么这个时候y_start = 1，但是第二个和第三个点已经在“首先先按照x的收尾添加x方向要被移除的点”这里被删除了，所以y_start = 1是不对的应该往后找让y_start = 3

2023-11-09 04:51 UTC, JohnnyShi approved these changes

2023-11-09 05:26 UTC, merged