GraphTraversal
JohnnyShi/USACO pull request #15
Opened 2023-11-09 10:04 UTC by Reditiny

not complete yet

2023-11-30 06:56 UTC, Reditiny commented on Silver/2022/February/01_Redistributing_Gifts/RedistributingGifts.java
> +        order.add(i);
这是一个图不是一个链，比如1->3，2->3，如果先放遍历完就是1->3->2，后放是3->1->2，最终要得到拓扑顺序1->2->3或者2->1->3，这样会发现先放是不行，需要后放再翻转

2023-11-30 10:40 UTC, Reditiny commented on Silver/2022/February/01_Redistributing_Gifts/RedistributingGifts3.java
调了很久还是会有两个case超时

2023-12-01 14:30 UTC, JohnnyShi requested changes

2023-12-01 14:30 UTC, JohnnyShi commented on Silver/2022/February/01_Redistributing_Gifts/RedistributingGifts2.java
> +        // 因为每次遍历都是从头开始遍历，假设 cow4 在 cow2 前被遍历到（反过来也一样），那么遍历到 cow4 时，cow1 和 cow2 的连通性已经被确定了
能不能举像底下一样的有3个牛的例子？

2023-12-04 10:51 UTC, Reditiny commented on Silver/2020/January/03_wormhole_sort/WormholeSort3.java
> +            if (!uf.connected(i, orders[i])) {
uf是克鲁斯卡尔算法中确定当前边是否需要加入集合的，这个地方的uf是用于判断所有的wayPoints是否在同一个集合内，因为这个题不是求最小生成树，而是在构建最小生成树的过程中在合适的位置停止，86行就是停止条件。

2023-12-06 10:15 UTC, JohnnyShi requested changes

2023-12-06 10:36 UTC, Reditiny commented on Silver/2022/February/01_Redistributing_Gifts/RedistributingGifts.java
> +     * 2. 反向图dfs，从起点开始，记录所有能到达的点，这些点就是一个强连通分量
![1701858576320](https://github.com/JohnnyShi/USACO/assets/140785332/3354dbbd-2ffc-49c4-975e-45ed88b65e49)
依照这个算法步骤，首先 dfs1 对应 step1 获得遍历顺序，然后再翻转，翻转和里面提到的出栈操作是一样的。  
然后得到根据 order 进行 dfs2 对应 step2 标记相应顶点得到强连通分量，我这里同时用了一个visited和hashset标记，  
visited是避免重复计算的，hashset 存放每次遍历到的点，hashset 中的点就属于同一个强连通分量

2023-12-06 10:42 UTC, Reditiny commented on Silver/2022/February/01_Redistributing_Gifts/RedistributingGifts2.java
> +        // 因为每次遍历都是从头开始遍历，假设 cow4 在 cow2 前被遍历到（反过来也一样），那么遍历到 cow4 时，cow1 和 cow2 的连通性已经被确定了
最外层的 for 每遍历一个牛，记做牛1，就会使得原本需要牛1做中间牛的牛2和牛3可以直接连接起来，下次遍历的时候，牛2和牛3就是直接相连的，表现出来就是每次迭代就能让中间牛减少一个

2023-12-06 10:49 UTC, Reditiny commented on Silver/2020/January/03_wormhole_sort/WormholeSort3.java
> +            if (!uf.connected(i, orders[i])) {
哦，明白了，我这个还是二分的解法，稍后再补充

2023-12-06 14:45 UTC, JohnnyShi commented on Silver/2022/February/01_Redistributing_Gifts/RedistributingGifts.java
> +     * 2. 反向图dfs，从起点开始，记录所有能到达的点，这些点就是一个强连通分量
好的，看懂了，要么把上面的链接作为注释写到这个题解里，以后可以参考

2023-12-06 14:45 UTC, JohnnyShi commented on Silver/2022/February/01_Redistributing_Gifts/RedistributingGifts2.java
> +        // 因为每次遍历都是从头开始遍历，假设 cow4 在 cow2 前被遍历到（反过来也一样），那么遍历到 cow4 时，cow1 和 cow2 的连通性已经被确定了
我读题解，感觉只是字面意思在通过桥接的牛把其他两个牛连起来，没有着重于消减中间牛

2023-12-08 11:05 UTC, Reditiny commented on Silver/2020/January/03_wormhole_sort/WormholeSort.java
> +    // unorderedCompare 记录每个节点是否需要排序，用于判断是否将节点放入图中，需要排序的节点才放入图
确实可能会有较多的重复计算，因为只考虑了点进入图，没考虑连通性。 WormholeSort4 是参考 python 代码用 uf 优化的

2023-12-09 02:11 UTC, JohnnyShi requested changes

2023-12-09 02:11 UTC, JohnnyShi commented on Silver/2022/February/01_Redistributing_Gifts/RedistributingGifts2.java
> +public class RedistributingGifts2 {
这个方法和前面SCC方法其实比较类似：
1. 最终目标是找到reachable[a][b]和reachable[b][a]同时满足的一对打印，意味着成环
2. 设置初始状态后（根据preference反向设置），通过图的传递性更新状态
需要在注释里解释3个点：
1. 为什么可以通过反向设置（这点36行已做到，不用更新）
2. 为什么可以依靠传递性？这里的传递性，类似36行，只是表示从A点发射的一条路径可以通过B点，并不表示实质上的A的东西会到达B点
3. 更新状态时，为什么是cow2在外层循环，而不是按照cow1, cow2 和cow3的顺序套循环，以及为何这样做就能保证遍历到所有的转移状态。
- 这里一个合适的例子可以是，假设一共就3头牛，称为A,B,C, A喜欢B的礼物，B喜欢C的礼物，C又喜欢A的礼物，则reachable[B][A] = true, reachable[C][B] = true, reachable[A][C] = true。通过传递性，得到reachable[C][A] = true, 说明C最后会得到A的礼物。
- 这个传递性是单向的，即虽然最终reachable[A][C]和reachable[C][A]都为true，但是A不会获得C的礼物，只有C获得A的礼物，因此最后的循环还是要从preference走，而不是用2个for循环寻找互通的AC和CA

请根据上面写的内容再调整43-48行的注释

2023-12-09 11:32 UTC, JohnnyShi approved these changes

2023-12-09 11:32 UTC, merged