Functional_Graphs
JohnnyShi/USACO pull request #18
Opened 2023-11-16 10:06 UTC by Reditiny

2023-11-21 07:57 UTC, JohnnyShi requested changes

2023-11-21 07:57 UTC, JohnnyShi commented on Silver/2022/US Open/01_Visits/Visits.java
> +        // 遍历环找到环内最小值
这里是否需要比较单链最小总和与单链+环的最值？
比如说这种情况：
2 -> 5 -> 4 -> 1 -> 3
                 |               |
                  - - - - - -
如果从头开始算，那么会得到2 + 5 + 4 + 1 = 12
如果停在交叉点处，会得到两段，即2 -> 5 和 4 -> 1 -> 3 -> 4，抛掉环内最小值，此时会得到2 + (3 + 4) = 9

上面例子转化成牛的访问顺序，即为（2,5,4,1,3），和（3,4,1,2,5）
此时刨除掉环内最小值未必是最优的

2023-11-21 08:03 UTC, Reditiny commented on Silver/2017/December/03_The_Bovine_Shuffle/TheBovineShuffle.java
> +
因为每头牛都有一个后继，所以不存在单链，每个连通图都一定是有环的

2023-11-21 08:15 UTC, Reditiny commented on Silver/2017/December/03_The_Bovine_Shuffle/TheBovineShuffle.java
> +
所以每头牛都会在第一次访问过后mark住

2023-11-21 08:16 UTC, Reditiny commented on Silver/2022/US Open/01_Visits/Visits.java
> +        // 遍历环找到环内最小值
因为一定有环，所以刨除掉环内最小值是最优的

2023-11-22 16:51 UTC, JohnnyShi approved these changes

2023-11-22 16:51 UTC, merged