Bronze_Supplement
JohnnyShi/USACO pull request #19
Opened 2023-11-22 02:34 UTC by Reditiny

2023-11-22 17:07 UTC, JohnnyShi requested changes

2023-11-22 17:07 UTC, JohnnyShi commented on Bronze/2018/December/01_mixing_milk/MixingMilk.java
> +    public static void main(String[] args) throws Exception {
这个实现有点过于复杂了；我觉得就是两种实现方法，第一个直接for 100次，肯定不超时；第二个用set存访问过的tuple状态然后early stop

2023-11-23 09:46 UTC, Reditiny commented on Bronze/2018/December/01_mixing_milk/MixingMilk.java
> +    public static void main(String[] args) throws Exception {
添加了一个直接for 100次的实现；存访问过的状态应该不需要用set，只需要存初始状态，因为第一次会重复的状态就是初始状态，原本的实现就是通过找cycle来实现early stop。

2023-11-27 07:28 UTC, Reditiny commented on Bronze/2023/US Open/03_rotate_and_shift/RotateAndShift.java
尝试了很多种优化方案，这个解仍然会超时。

2024-01-13 01:23 UTC, JohnnyShi requested changes

2024-01-13 01:23 UTC, JohnnyShi commented on Bronze/2018/December/01_mixing_milk/MixingMilk.java
> +    private static boolean matchInit() {
比如sample case,
10 3
11 4
12 5
开始循环后其实碰到0 0 12才开始循环

2024-01-13 01:23 UTC, JohnnyShi commented on Bronze/2020/January/02_photoshoot/Photoshoot.java
> +    static void makeAByA0(int a0) {
N 可能会大，因此检查return false的条件可以更早的放在makeAByA0这个函数中。可以参考一下python代码

2024-01-13 01:23 UTC, JohnnyShi commented on Bronze/2021/December/02_air_cownditioning/AirCownditioning.java
> +import java.io.BufferedReader;
参考python代码加入数学方法

2024-01-13 01:23 UTC, JohnnyShi commented on Bronze/2021/December/03_walking_home/WalkingHome.java
> +     */
注释标一下哪行是RDRD哪行是DRDR

2024-01-13 01:23 UTC, JohnnyShi commented on Bronze/2023/US Open/03_rotate_and_shift/RotateAndShift.java
参考python代码03_rotate_and_shift_jump_formula，实现数学方法

2024-01-13 01:23 UTC, JohnnyShi commented on Bronze/2023/US Open/03_rotate_and_shift/RotateAndShift.java
> +public class RotateAndShift {
参考python代码优化模拟方法

2024-01-14 07:35 UTC, Reditiny commented on Bronze/2018/December/01_mixing_milk/MixingMilk.java
> +    private static boolean matchInit() {
添加了 [MixingMilk3.java]，实现这个功能

2024-01-14 07:39 UTC, Reditiny commented on Bronze/2023/US Open/03_rotate_and_shift/RotateAndShift.java
> +public class RotateAndShift {
按照 python 代码添加了 RotateAndShift3.Java 依然会超时，两个解法本质上没有区别，因为这个题的转移是可逆的，不像 MixMilk 那个题的转移不可逆，所以在这个题中，如果有某个中间状态会第二次出现，那在此之前初始状态也一定第二次出现过。

2024-01-14 15:14 UTC, JohnnyShi commented on Bronze/2023/US Open/03_rotate_and_shift/RotateAndShift.java
> +public class RotateAndShift {
我的意思是有点难看懂，复杂度模拟是没有提升空间的

2024-01-15 09:44 UTC, JohnnyShi requested changes

2024-01-15 09:44 UTC, JohnnyShi commented on Bronze/2018/December/01_mixing_milk/MixingMilk.java
> +    private static boolean matchInit() {
我会觉得MixingMilk1这个解法如果只去判断是否和最初始的状态一致，就有点鸡肋，因为很大概率是碰不到，可以去掉。

2024-01-15 09:44 UTC, JohnnyShi commented on Bronze/2018/December/01_mixing_milk/MixingMilk3.java
> +public class MixingMilk3 {
这里注释一下这种特殊情景：
学生可能会问，为什么要pour三次之后才判断是否在set里出现过，而不是每pour一次就判断一次。
试想如果1号是空的，2号和3号都是满的，就意味着从1号倒入2号，或者2号倒入3号，都是不变的，所以在用set判断当前状态是否出现的时候，不能拿任意一个位置去判断，而是只拿倒完3次后的位置去判断。
并且当出现过重复的状态之后，也不需要记录startCycle和endCycle，都拿pour3次之后的状态去比较，然后mod 3，最后再执行一次pour。
所以把现在的MixingMilk3参考现在的1综合一下成为一种方法

2024-01-15 09:44 UTC, JohnnyShi commented on Bronze/2023/US Open/03_rotate_and_shift/RotateAndShift3.java
> +import java.io.BufferedReader;
1和3最终选一种方法就行，和python的模拟法对齐

2024-01-15 15:08 UTC, Reditiny commented on Bronze/2018/December/01_mixing_milk/MixingMilk3.java
> +public class MixingMilk3 {
方法1只考虑初始状态确实是很大概率碰不到。这里的startCycle和endCycle是需要的，用于记录剩余次数和周期大小，进一步优化了startCycle和endCycle的逻辑。

2024-01-15 15:08 UTC, Reditiny commented on Bronze/2023/US Open/03_rotate_and_shift/RotateAndShift3.java
> +import java.io.BufferedReader;
保留方法3吧，和python一致

2024-01-16 01:02 UTC, JohnnyShi requested changes

2024-01-16 01:02 UTC, JohnnyShi commented on Bronze/2018/December/01_mixing_milk/MixingMilk3.java
> +        }
这段还需要吗？如果break了说明要么到达33次，要么已经重复了，就不需要再pour3了，否则其实相比于暴力方法没有提升？

2024-01-16 01:09 UTC, Reditiny commented on Bronze/2018/December/01_mixing_milk/MixingMilk3.java
> +        }
这个是剩余次数，比如33次，第6次的时候开始循环，循环大小是10，那么33次就被分成了6+10*2+7，6已经在寻找循环的时候倒过了，7就是这个pourTimes

2024-01-16 01:11 UTC, Reditiny commented on Bronze/2018/December/01_mixing_milk/MixingMilk3.java
> +        }
如果没找到循环，那么break之后pourTimes的计算结果就是0

2024-01-26 16:52 UTC, JohnnyShi requested changes

2024-01-26 16:52 UTC, JohnnyShi commented on Bronze/2020/US Open/01_social_distance_i/SocialDistancingI.java
> +import java.io.BufferedReader;
参考python增加一个官方的5种情况题解；你的解法也很好，补充一个python版本

2024-01-29 13:42 UTC, merged