bronze_2016_supplement
JohnnyShi/USACO pull request #37
Opened 2023-12-28 09:42 UTC by Reditiny

2024-01-09 07:37 UTC, JohnnyShi requested changes

2024-01-09 07:37 UTC, JohnnyShi commented on Bronze/2016/US Open/03_field_reduction/field_reduction.cpp
> +#include <iostream>
铜组题只用去掉一个点吧？是不是看成银组题了

2024-01-15 14:40 UTC, Reditiny commented on Bronze/2016/February/01_milk_pails/milk_pails.cpp
> +#include <iostream>
递归方法C++也会有case超时

2024-01-21 14:55 UTC, JohnnyShi requested changes

2024-01-21 14:55 UTC, JohnnyShi commented on Bronze/2016/US Open/03_field_reduction/field_reduction.cpp
> +#include <fstream>
silver的解法是不是都移动到silver的题目里？

2024-01-21 14:55 UTC, JohnnyShi commented on Bronze/2016/US Open/03_field_reduction/field_reduction_bronze.cpp
> +#include <iostream>
参考python的field_reduction_solution，写更简洁的写法

2024-01-22 14:02 UTC, Reditiny commented on Bronze/2016/US Open/03_field_reduction/field_reduction_bronze.cpp
> +#include <iostream>
python解法使用了sort，复杂度高，补充了相关的c++与python的方法

2024-01-22 16:41 UTC, JohnnyShi approved these changes
最后一条comment

2024-01-22 16:41 UTC, JohnnyShi commented on Bronze/2016/US Open/03_field_reduction/field_reduction_bronze.cpp
> +#include <iostream>
sort有Java方法吗？

2024-01-23 14:25 UTC, merged