bronze_2017_supplement
JohnnyShi/USACO pull request #38
Opened 2024-01-01 11:47 UTC by Reditiny

2024-01-08 16:54 UTC, JohnnyShi requested changes

2024-01-08 16:54 UTC, JohnnyShi commented on Bronze/2017/US Open/01_the_lost_cow/the_lost_cow.cpp
> +            current_position = farmer_position + static_cast<int>(pow(2, power));
这里为什么要static_cast?

2024-01-08 16:54 UTC, JohnnyShi commented on Bronze/2017/US Open/02_bovine_genomics/bovine_genomics.cpp
> +#include <map>
去除不用的库

2024-01-17 13:20 UTC, Reditiny commented on Bronze/2017/February/02_why_did_the_cow_cross_the_road_ii/why_did_the_cow_cross_the_road_ii.cpp
> +#include <iostream>
这个应该不能叫做stack方法，它不满足stack的规则，java和python提供了这种特殊的“出栈”方式，c++的stack没有提供

2024-01-26 17:16 UTC, JohnnyShi requested changes

2024-01-26 17:16 UTC, JohnnyShi commented on Bronze/2017/February/02_why_did_the_cow_cross_the_road_ii/stack/WhyDidTheCowCrossTheRoadII2.java
> +import java.io.BufferedReader;
是不是还缺个C++的实现？

2024-01-29 13:39 UTC, Reditiny commented on Bronze/2017/February/02_why_did_the_cow_cross_the_road_ii/stack/WhyDidTheCowCrossTheRoadII2.java
> +import java.io.BufferedReader;
c++没有提供这种出栈方式，我用了vector模拟

2024-01-29 13:45 UTC, merged