bronze_2018_supplement
JohnnyShi/USACO pull request #39
Opened 2024-01-02 14:08 UTC by Reditiny

2024-01-15 01:20 UTC, JohnnyShi requested changes

2024-01-15 01:20 UTC, JohnnyShi commented on Bronze/2018/US Open/03_family_tree/family_tree.cpp
> +#include <iostream>
以这种解法为最优解法，同时参考python的iteration和calc_distance实现3种语言的暴力搜索法和树状数据结构的方法

2024-01-22 14:05 UTC, Reditiny commented on Bronze/2018/December/01_mixing_milk/mixing_milk.cpp
> +#include <iostream>
是之前java的pr

2024-01-22 15:57 UTC, JohnnyShi requested changes

2024-01-22 15:57 UTC, JohnnyShi commented on Bronze/2018/January/03_out_of_place/out_of_place_bs.cpp
> +    set<int> uniqueElements;
非必要的时候就用unordered_set，silver的treeset再用这个排序set

2024-01-22 15:57 UTC, JohnnyShi commented on Bronze/2018/US Open/01_team_tic_tac_toe/team_tic_tac_toe.cpp
> +    for (int i = 0; i < 3; i++) {
这样的比较太长且不易维护，hardcode太多。其实就是for循环，把board[i][0], board[i][1] 和board[i][2]添加到一个unordered_set里，然后检查set的大小是不是2且target1和target2都在set里面

2024-01-22 15:57 UTC, JohnnyShi commented on Bronze/2018/US Open/01_team_tic_tac_toe/team_tic_tac_toe.py
> +    return (c1 == target1 and c2 == target2 and c3 == target2) or \
和C++同理，使用更易维护的set方法判断

2024-01-22 15:57 UTC, JohnnyShi commented on Bronze/2018/US Open/03_family_tree/family_tree.cpp
> +#include <iostream>
没看到另外两种解法

2024-01-24 15:33 UTC, JohnnyShi approved these changes

2024-01-24 15:33 UTC, JohnnyShi commented on Bronze/2018/US Open/03_family_tree/FamilyTreeC.java
> +    static class TreeNode {
TreeNode直接定义在class之外，成为class TreeNode

2024-01-29 14:08 UTC, merged