simulation hard and search normal
JohnnyShi/USACO pull request #5
Opened 2023-10-23 09:23 UTC by Reditiny

2023-10-24 10:58 UTC, JohnnyShi requested changes

2023-10-24 10:58 UTC, JohnnyShi commented on Bronze/2018/January/02_lifeguards/Lifeguards.java
> +            for (int j = i + 1; j < intervals.size(); j++) {
这里注释一下方法：
按照开始排序之后，遍历所有区间，假设移除当前区间，依次遍历后续区间，直到下一个区间的结束区间大于当前结束区间。举例：
例子1：移除其中一个区间仅减少该区间所覆盖面积
```
---
         ---
                   ---
```
例子2：移除第二个区间会影响到后面很多时间段的覆盖度，因此要一直检查后续区间，直到下一区间在被移除区间结束后结束
```
---
  -----------------
          ---
                       ---
```

2023-10-24 10:58 UTC, JohnnyShi commented on Bronze/2018/January/02_lifeguards/Lifeguards.java
> +public class Lifeguards {
方法2是n^2的方法，即每次移除一个区间，从头到尾再算一遍覆盖度，这个方法的目的是把算法清楚的分成2部分，一部分是选择一个区间移除，另一部分是用双指针把移除后的list遍历一遍得到覆盖度

2023-10-24 10:58 UTC, JohnnyShi commented on Bronze/2018/January/02_lifeguards/Lifeguards.java
> +            for (int j = i + 1; j < intervals.size(); j++) {
这个解法花了我很长时间才看懂，我觉得是不是有更清楚的写法/注释方法来表达？
算法我看到有这几部分：
1. 有一个total_coverage在滑动的计算覆盖面，实际上最后的值就是所有区间的覆盖度
2. 有一个min_total_gap_after_removal在找移除某个区间得到的空隙加总
3. 最后的结果等于 1 - 2
在算1的时候，需要：
1. furthest_interval_end 表示当前区间之前的区间所覆盖到的最远距离
2. 每次累加是加上当前区间超过之前最远距离的部分，并更新最远距离为当前区间结尾
在算2的时候，需要：
1. total_gap_after_removal 累加移除该区间后所造成的累积缺口（不需要考虑当前区间之前的区间，因为已经按照区间开始排序，因此不会影响之前区间）；这个变量的目的是找到min_total_gap_after_removal
2. 性能优化：当被移除区间的结束时刻已经小于遍历区间所能触及的最远距离时，移除当前区间已经对后续区间无影响，因此可提前结束循环

你试着按照这个思路重新组织一下注释、变量名和代码，看能不能让这个解法更直接易懂

2023-10-25 03:54 UTC, JohnnyShi requested changes

2023-10-25 03:54 UTC, JohnnyShi commented on Bronze/2018/US Open/01_team_tic_tac_toe/TeamTicTacToe2.java
> +        putWin(winChar, singleWin, teamWin);
九宫格里一共有8个要检查的字符串，3行3列2斜，可以先用一个函数把8个要检查的字符串都取出来，然后对每个字符串再调用putWin函数，这样更简洁

2023-10-25 03:54 UTC, JohnnyShi commented on Bronze/2019/December/01_cow_gymnastics/CowGymnastics.java
> +                if (better[i][j] == !better[j][i]) {
```suggestion
                if (better[i][j] != better[j][i]) {
```

2023-10-25 03:54 UTC, JohnnyShi commented on Bronze/2020/February/01_triangles/Triangles.java
> +     * 1 2    1      1 3      2
这个怎么理解？

2023-10-25 03:54 UTC, JohnnyShi commented on Bronze/2020/February/01_triangles/Triangles.java
> +    public static int getArea(List<Integer> point1, List<Integer> point2, List<Integer> point3) {
如果按照x排序，则要考虑：
x1 == x2 且 x1 != x3, 然后检查y1 == y3 或 y1 == y2
x1 != x2 且 x2 == x3，然后检查y1 == y2 或 y1 == y3

2023-10-25 05:36 UTC, Reditiny commented on Bronze/2016/February/01_milk_pails/MilkPails.java
> +        for (int i = 0; i <= maxX; i++) {
+ MilkPails2.java
`import java.io.BufferedReader;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.StringTokenizer;

/**
 * @author Red
 * @version 1.0
 */
public class MilkPails2 {
    public static void main(String[] args) throws Exception {
        BufferedReader r = new BufferedReader(new FileReader("pails.in"));
        PrintWriter pw = new PrintWriter("pails.out");
        StringTokenizer st = new StringTokenizer(r.readLine());
        int x = Integer.parseInt(st.nextToken());
        int y = Integer.parseInt(st.nextToken());
        int m = Integer.parseInt(st.nextToken());
        int maxX = m / x;
        // int maxY = m / y;
        int ans = 0;
        // 搜索范围内遍历得到最大值
        for (int i = 0; i <= maxX; i++) {
            // 缩小内层遍历的范围 maxY -> (m - x * i) / y
            for (int j = 0; j <= (m - x * i) / y; j++) {
                if (x * i + y * j > m) {
                    break;
                }
                if (x * i + y * j > ans) {
                    ans = x * i + y * j;
                }
            }
        }
        pw.println(ans);
        pw.close();
    }
}
`

2023-10-25 05:36 UTC, Reditiny commented on Bronze/2016/February/01_milk_pails/MilkPails.java
> +        for (int i = 0; i <= maxX; i++) {
pr里新增文件是这样吗？

2023-10-25 05:40 UTC, Reditiny commented on Bronze/2020/February/01_triangles/Triangles.java
> +     * 1 2    1      1 3      2
这里格式化错了，应该是这样，由于排序过，所以只会出现这四种排列
   3      2 3       2      1 3
1 2       1       1 3      2

2023-10-26 09:33 UTC, JohnnyShi requested changes

2023-10-26 09:33 UTC, JohnnyShi commented on Bronze/2022/February/01_sleeping_in_the_class/SleepingInClass.java
> +            for (int numHours = 0; numHours <= logSum; numHours++) {
条件可优化为 <= logSum / 2

2023-10-26 13:54 UTC, JohnnyShi requested changes

2023-10-26 14:33 UTC, JohnnyShi requested changes

2023-10-26 14:33 UTC, JohnnyShi commented on Bronze/2018/December/03_back_and_forth/BackAndForth.java
> +public class BackAndForth {
再实现一个非递归的set的方法，具体逻辑可以看python的实现

2023-10-26 14:33 UTC, JohnnyShi commented on Bronze/2016/US Open/02_bull_in_a_china_shop/BullInChinaShop.java
> +        pieces = new boolean[11][8][8];
为啥是11？

2023-10-26 14:33 UTC, JohnnyShi commented on Bronze/2016/US Open/02_bull_in_a_china_shop/BullInChinaShop.java
> +                            for (int jdy = s[j][1] - n + 1; jdy <= s[j][0]; jdy++) {
注释解释这个区域是怎么算来的

2023-10-26 14:33 UTC, JohnnyShi commented on Bronze/2016/US Open/02_bull_in_a_china_shop/BullInChinaShop.java
> +        pieces = new boolean[11][8][8];
好像没必要从index = 1开始

2023-10-26 14:57 UTC, JohnnyShi requested changes

2023-10-26 14:57 UTC, JohnnyShi commented on Bronze/2016/US Open/02_bull_in_a_china_shop/BullInChinaShop.java
> +        pieces = new boolean[11][8][8];
hardcode的地方都注释一下

2023-10-26 14:57 UTC, JohnnyShi commented on Bronze/2019/December/01_cow_gymnastics/CowGymnastics.java
> +public class CowGymnastics {
参考Python代码实现一个set的方法

2023-10-26 14:57 UTC, JohnnyShi commented on Bronze/2020/US Open/03_cowntact_tracing/CowntactTracing.java
> +            for (int k = 0; k <= 251; k++) {
能取到251吗？

2023-10-26 14:57 UTC, JohnnyShi commented on Bronze/2022/US Open/02_counting_liars/CountingLiars.java
> +        int ans = 0x3f3f3f3f;
这个代表什么数？

2023-10-26 14:57 UTC, JohnnyShi commented on Bronze/2022/US Open/02_counting_liars/CountingLiars.java
> +        }
这段还需要详细解释一下，以及为什么gCows是正序、lCows是倒序，又为什么需要倒序遍历？

2023-10-27 03:02 UTC, Reditiny commented on Bronze/2022/US Open/02_counting_liars/CountingLiars.java
> +        int ans = 0x3f3f3f3f;
给定一个较大的初始值，已经修改成Integer.MAX_VALUE了

2023-10-27 03:32 UTC, Reditiny commented on Bronze/2022/February/01_sleeping_in_the_class/SleepingInClass.java
> +            for (int numHours = 0; numHours <= logSum; numHours++) {
应该不行，虽然 logSum / 2 + 1 到 logSum - 1 之间均为 false，但是 numHours == logSum 需要走一遍逻辑

2023-10-29 11:11 UTC, JohnnyShi commented on Bronze/2023/US Open/02_moo_language/MooLanguage.java
> +                // 两个type2句子需要一个连词和一个句号  一个type2句子需要一个句号
这里为什么要考虑2个type 2句子的连词问题？

2023-10-29 17:05 UTC, JohnnyShi requested changes

2023-10-29 17:05 UTC, JohnnyShi commented on Bronze/2022/US Open/02_counting_liars/CountingLiars.java
> +public class CountingLiars {
可参考最新的python代码，提高可读性

2023-10-29 17:05 UTC, JohnnyShi commented on Bronze/2018/January/02_lifeguards/Lifeguards.java
> +public class Lifeguards {
可参考最新Python代码，提高可读性

2023-10-30 01:48 UTC, Reditiny commented on Bronze/2020/February/01_triangles/Triangles.java
>       *   3    2 3    2      1 3
按照 x 坐标排序 如果 x 坐标相同则按照 y 坐标排序，这种排序规则下可能出现的排列情况只有这四种，目的是通过这个排序来缩小可能的排列范围，进而最终判断时只用考虑“y1 == y2”，“x1 == x2”和“y1 == y3 && x2 == x3”三个条件，其他的条件在这个排序规则下都是不可行的。

2023-10-30 01:56 UTC, Reditiny commented on Bronze/2023/US Open/02_moo_language/MooLanguage.java
> +                // 两个type2句子需要一个连词和一个句号  一个type2句子需要一个句号
这里不是考虑连词，而是考虑句号。当前的目的是对于给定的type1（不及物动词）数量，寻找type2（及物动词）最多能有多少个，有两个限制条件一个是动词数另一个是句号数，连词的出现只是增强了句号的利用率。

2023-10-30 12:01 UTC, JohnnyShi requested changes

2023-11-01 05:33 UTC, JohnnyShi requested changes
Almost there

2023-11-01 05:33 UTC, JohnnyShi commented on Bronze/2016/US Open/02_bull_in_a_china_shop/BullInChinaShop2.java
> +                for (int l = 0; l < n; l++) {
用r c来指代行和列吧

2023-11-01 05:33 UTC, JohnnyShi commented on Bronze/2016/US Open/02_bull_in_a_china_shop/BullInChinaShop2.java
> +                //  |   ----   |  top
在36行bottom按max取的，所以从坐标来看应该是下边界对应的bottom，上边界对应的top？

2023-11-01 05:33 UTC, JohnnyShi commented on Bronze/2020/February/01_triangles/Triangles.java
> +                && (point3.get(1).equals(point1.get(1)) || point2.get(1).equals(point1.get(1)))) {
和54-58格式一致吧，：
dx = Math.abs(point2.get(0) - point1.get(0));
if (point3.get(1).equals(point1.get(1)) || point2.get(1).equals(point1.get(1)) {
    dy = Math.abs(point2.get(1) - point3.get(1));
}

2023-11-01 05:33 UTC, JohnnyShi commented on Bronze/2023/US Open/02_moo_language/MooLanguage.java
> +                sentence.add(iverb.remove(iverb.size() - 1));
这里注释一下为什么不remove(0)，考虑到性能？

2023-11-01 05:33 UTC, JohnnyShi commented on Bronze/2023/US Open/02_moo_language/MooLanguage.java
> +                }
String.join()?

2023-11-01 05:33 UTC, JohnnyShi commented on Bronze/2023/US Open/02_moo_language/MooLanguage.java
> +                if (j % 2 == 0 && combine > 0) {
感觉应该再检查一下j是否为最后一个句子，不然不好确定最后要不要加连词

2023-11-01 05:33 UTC, JohnnyShi commented on Bronze/2023/US Open/02_moo_language/MooLanguage.java
> +                    conj.remove(conj.size() - 1);
可以缩成一行，因为remove函数会返回值

2023-11-01 05:33 UTC, JohnnyShi commented on Bronze/2022/US Open/02_counting_liars/CountingLiars.java
> +public class CountingLiars {
这个已经验证过了，这样写OK的。之前说会参考Python再写一个慢但是直接的解法的也请实现一下

2023-11-01 11:53 UTC, Reditiny commented on Bronze/2016/US Open/02_bull_in_a_china_shop/BullInChinaShop2.java
> +                //  |   ----   |  top
max取说明bottom数值上在变大，从逻辑（数值）上看bottom是对应下边界，从图像上看bottom是在上面，因为二维数组最上面一行是索引是0。

2023-11-01 11:56 UTC, Reditiny commented on Bronze/2016/US Open/02_bull_in_a_china_shop/BullInChinaShop2.java
> +                //  |   ----   |  top
这样确实容易混淆，我把命名改一下，让它看上去更直观。

2023-11-01 12:15 UTC, Reditiny commented on Bronze/2023/US Open/02_moo_language/MooLanguage.java
> +                if (j % 2 == 0 && combine > 0) {
如果j是最后一个句子加完conj之后会离开循环，那么第137行就会把多余的conj删除。因为这里以及考虑到结尾方式要么为"sentence conj"要么为"sentence. "

2023-11-02 10:24 UTC, JohnnyShi requested changes

2023-11-03 05:24 UTC, JohnnyShi approved these changes
谢谢，辛苦了

2023-11-03 05:27 UTC, merged