Ad hoc
JohnnyShi/USACO pull request #6
Opened 2023-10-31 07:17 UTC by Reditiny

2023-11-01 04:48 UTC, JohnnyShi requested changes
整体都不错，主要Hoofball加一个实现，一些代码和注释的微调，然后FEB需要再迭代一下

2023-11-01 04:48 UTC, JohnnyShi commented on Bronze/2018/US Open/02_milking_order/MilkingOrder.java
> +        }
同理

2023-11-01 04:48 UTC, JohnnyShi commented on Bronze/2019/February/01_sleepy_cow_herding/SleepyCowHerding.java
> +        // 当 maxGap 较大时 总可以最少两步就放在一起 1___2______3 -> 2_1____3 -> 231
用数字有点歧义，比如我会觉得需要变成123的顺序；用牛的名字，BEM来举例吧

2023-11-01 04:48 UTC, JohnnyShi commented on Bronze/2019/February/01_sleepy_cow_herding/SleepyCowHerding.java
> +        // 最多需要 maxGap 步 1___2______3 -> 2_____13 -> 23____1 -> 3___21 ....
1__2____3 -> 21___3 -> 12__3 -> 21_3 -> 123

2023-11-01 04:48 UTC, JohnnyShi commented on Bronze/2019/February/01_sleepy_cow_herding/SleepyCowHerding.java
> +        // 最多需要 maxGap 步 1___2______3 -> 2_____13 -> 23____1 -> 3___21 ....
感觉固定住一端，然后让另一端的两只牛一步步逼近，更容易理解

2023-11-01 04:48 UTC, JohnnyShi commented on Bronze/2019/January/02_sleepy_cow_sorting/SleepyCowSorting.java
> +        // 1 6 7 8 9 10 本身已经时升序，前面的牛只需要移动进这个升序序列之中
加一句解释为什么碰到一个cows[i] > lastNumber就可以break，即为什么能确认换位次数是n - endOrderCount

2023-11-01 04:48 UTC, JohnnyShi commented on Bronze/2023/US Open/01_feb/FEB.java
> +            int length = endIndex - startIndex + 1;
为啥要+1？BFB的话，endIndex - startIndex = 2?

2023-11-01 04:48 UTC, JohnnyShi commented on Bronze/2023/US Open/01_feb/FEB.java
> +    static TreeSet<Integer> ans = new TreeSet<>();
这个没用到吧

2023-11-01 04:48 UTC, JohnnyShi commented on Bronze/2023/US Open/01_feb/FEB.java
> +        int suffixCount = 0;
如果执行到这里，应该意味着从start往后都是F了，还需要while循环算suffixCount吗？

2023-11-01 15:55 UTC, JohnnyShi requested changes
一点小问题

2023-11-01 15:55 UTC, JohnnyShi commented on Bronze/2018/February/02_hoofball/Hoofball2.java
> +    }
好像没用到

2023-11-01 15:55 UTC, JohnnyShi commented on Bronze/2018/US Open/02_milking_order/MilkingOrder.java
> +     * 将 Hierarchy 中 1 前面的牛从前完后依次放入队列中
typo：往后

2023-11-01 15:55 UTC, JohnnyShi commented on Bronze/2018/US Open/02_milking_order/MilkingOrder.java
> +        cowOrder = new int[n + 1];
用一个cowOrder应该就够了，多一个arraylist复杂度增益不大

2023-11-02 01:19 UTC, Reditiny commented on Bronze/2018/US Open/02_milking_order/MilkingOrder.java
> +        cowOrder = new int[n + 1];
两个数组有不同的用处，cowToOrder是为了快速查找某头牛所要求的位置

2023-11-02 01:21 UTC, Reditiny commented on Bronze/2018/US Open/02_milking_order/MilkingOrder.java
> +        cowOrder = new int[n + 1];
加了额外的注释说明两个数组各自的作用

2023-11-02 01:59 UTC, JohnnyShi requested changes

2023-11-02 01:59 UTC, JohnnyShi commented on Bronze/2019/February/01_sleepy_cow_herding/SleepyCowHerding.java
> +        // 当 maxGap 较大时 总可以最少两步就放在一起 1___2______3 -> 2_1____3 -> 231
这里注释还需要改一下

2023-11-02 01:59 UTC, JohnnyShi commented on Bronze/2019/February/01_sleepy_cow_herding/SleepyCowHerding.java
> +        // 最多需要 maxGap 步 1___2______3 -> 2_____13 -> 23____1 -> 3___21 ....
这里注释还需要改一下

2023-11-02 02:21 UTC, JohnnyShi commented
All looks good! 辛苦了，等search的PR结束了再merge这个。
因为现在search的branch是main，以后要给每个topic单独开branch，这样就不会互相依赖

2023-11-02 15:04 UTC, JohnnyShi commented on Bronze/2019/February/01_sleepy_cow_herding/SleepyCowHerding.java
> +        int gapB = cows.get(1) - cows.get(0);
这里还是叫gap1和gap2就行，BEM只是代表三个端点，叫gapB反倒不理解意思

2023-11-03 05:31 UTC, JohnnyShi approved these changes

2023-11-03 05:33 UTC, merged