Graphs
JohnnyShi/USACO pull request #7
Opened 2023-11-01 10:40 UTC by Reditiny

2023-11-02 02:45 UTC, JohnnyShi requested changes
除了the great revegetation其他都ok

2023-11-02 02:45 UTC, JohnnyShi commented on Bronze/2019/February/02_the_great_revegetation/TheGreatRevegetation.java
> +        // 从前完后依次确定牧场的种子
typo

2023-11-02 02:45 UTC, JohnnyShi commented on Bronze/2019/February/02_the_great_revegetation/TheGreatRevegetation.java
> +                if (neighbor < grasses.size()) {
怎么理解？

2023-11-02 14:56 UTC, JohnnyShi reviewed
Some questions on the great revegetation

2023-11-02 14:56 UTC, JohnnyShi commented on Bronze/2019/February/02_the_great_revegetation/TheGreatRevegetation.java
>          grasses.add(1);
是不是可以参考python代码，把增加第一项也放到循环里

2023-11-02 14:56 UTC, JohnnyShi commented on Bronze/2019/February/02_the_great_revegetation/TheGreatRevegetation.java
>          for (int i = 1; i < n; i++) {
为什么不从0开始，且只循环了n-1次？

2023-11-02 14:56 UTC, JohnnyShi commented on Bronze/2019/February/02_the_great_revegetation/TheGreatRevegetation.java
>                  if (neighbor < grasses.size()) {
还是不太理解neighbor小于grass的长度说明了什么？在python实现中我考虑的就是某种颜色能不能被使用

2023-11-03 01:29 UTC, Reditiny commented on Bronze/2019/February/02_the_great_revegetation/TheGreatRevegetation.java
>          for (int i = 1; i < n; i++) {
第一个牧场在33行直接种上了1号种子

2023-11-03 01:32 UTC, Reditiny commented on Bronze/2019/February/02_the_great_revegetation/TheGreatRevegetation.java
>                  if (neighbor < grasses.size()) {
neighbor是牧场的序号，循环是在按序种种子，如果这个序号小于grass的长度，说明它已经进入了grass数组，说明它已经种过种子了

2023-11-03 01:32 UTC, Reditiny commented on Bronze/2019/February/02_the_great_revegetation/TheGreatRevegetation.java
>          grasses.add(1);
可以，进循环最后也是种1号

2023-11-03 03:39 UTC, JohnnyShi requested changes
把TheGreatRevegetation的循环包括进i=0，其他没问题

2023-11-03 03:39 UTC, JohnnyShi commented on Bronze/2019/February/02_the_great_revegetation/TheGreatRevegetation.java
>                  if (neighbor < grasses.size()) {
好的，看懂了，那也注释标注一下，因为grass是按顺序往后插入的，所以grass的长度表明了已有这么多牧场已经被填过，所以如果neighbor < grass长度则表示这个颜色已经被用过，不能在i再使用

2023-11-03 05:36 UTC, JohnnyShi approved these changes

2023-11-03 05:36 UTC, merged